app:
  storage:
    type: ${STORAGE_TYPE:s3}
    s3:
      bucket: ${S3_BUCKET_NAME:todo-bucket123}
      prefix: ${S3_PREFIX:attachments}
#    root-dir: ${LOCAL_STORAGE_PATH:./uploads}

spring:
  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-2}
      credentials:
        access-key: ${AWS_ACCESS_KEY:}
        secret-key: ${AWS_SECRET_KEY:}

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:25MB}
      max-request-size: ${MAX_REQUEST_SIZE:25MB}

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/todo_db}
    username: ${DATABASE_USERNAME:user-todo}
    password: ${DATABASE_PASSWORD:todo123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # dev-friendly; use 'validate' in prod; don't let Hibernate mutate schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      open-in-view: false

      # Optional: auto-run schema/data scripts if present (schema.sql, data.sql)
      sql:
        init:
          mode: never # set to 'always' if you add schema.sql/data.sql
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: true
    schemas: public
    default-schema: public
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/todo_db}
    user: ${DATABASE_USERNAME:user-todo}
    password: ${DATABASE_PASSWORD:todo123}

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: debug
    com.todo.security: debug
    com.todo.controller: debug
    # runs db/migration scripts automatically

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true
